name: Test CLI
on:
  push:
    branches:
      - '*'
jobs:
  lint:
    name: Lint sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
  test:
    name: Test local sources
    strategy:
      fail-fast: false
      max-parallel: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Test Go
        run: go test -race ./...
